#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''flexicomps

Copyright (C) 2008-2010
    Geoffrey Biggs
    RT-Synthesis Research Group
    Intelligent Systems Research Institute,
    National Institute of Advanced Industrial Science and Technology (AIST),
    Japan
    All rights reserved.
Licensed under the Eclipse Public License -v 1.0 (EPL)
http://www.opensource.org/licenses/eclipse-1.0.txt

File: typemap.py

Type map for the FlexiFilter component.

'''

__version__ = '$Revision: $'
# $Source$

typeMap = {
	'TimedShort':		(int, 0),
	'TimedLong':		(int, 0),
	'TimedUShort':		(int, 0),
	'TimedULong':		(int, 0),
	'TimedFloat':		(float, 0.0),
	'TimedDouble':		(float, 0.0),
	'TimedChar':		(str, ''),
	'TimedBoolean':		(bool, False),
	'TimedOctet':		(str, ''),
	'TimedString':		(str, ''),
	'TimedShortSeq':	(int, 0),
	'TimedLongSeq':		(int, 0),
	'TimedUShortSeq':	(int, 0),
	'TimedULongSeq':	(int, 0),
	'TimedFloatSeq':	(float, 0.0),
	'TimedDoubleSeq':	(float, 0.0),
	'TimedCharSeq':		(str, ''),
	'TimedBooleanSeq':	(bool, False),
	'TimedOctetSeq':	(str, ''),
	'TimedStringSeq':	(str, ''),
}


multMap = {
	'TimedShort':		{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedLong':		{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedUShort':		{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedULong':		{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedFloat':		{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': False, 'TimedDouble': False, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': False, 'TimedDoubleSeq': False, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedDouble':		{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': False, 'TimedDouble': False, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': False, 'TimedDoubleSeq': False, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedChar':		{'TimedShort': True, 'TimedLong': True, 'TimedLong': True, 'TimedULong': True,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': -1,
						'TimedBoolean': -1, 'TimedOctet': -1, 'TimedString': -1,
						'TimedShortSeq': True, 'TimedLongSeq': True, 'TimedLongSeq': True, 'TimedULongSeq': True,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': -1,
						'TimedBooleanSeq': -1, 'TimedOctetSeq': -1, 'TimedStringSeq': -1},
	'TimedBoolean':		{'TimedShort': True, 'TimedLong': True, 'TimedLong': True, 'TimedULong': True,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': -1,
						'TimedBoolean': -1, 'TimedOctet': -1, 'TimedString': -1,
						'TimedShortSeq': True, 'TimedLongSeq': True, 'TimedLongSeq': True, 'TimedULongSeq': True,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': -1,
						'TimedBooleanSeq': -1, 'TimedOctetSeq': -1, 'TimedStringSeq': -1},
	'TimedOctet':		{'TimedShort': True, 'TimedLong': True, 'TimedLong': True, 'TimedULong': True,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': -1,
						'TimedBoolean': -1, 'TimedOctet': -1, 'TimedString': -1,
						'TimedShortSeq': True, 'TimedLongSeq': True, 'TimedLongSeq': True, 'TimedULongSeq': True,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': -1,
						'TimedBooleanSeq': -1, 'TimedOctetSeq': -1, 'TimedStringSeq': -1},
	'TimedString':		{'TimedShort': True, 'TimedLong': True, 'TimedLong': True, 'TimedULong': True,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': -1,
						'TimedBoolean': -1, 'TimedOctet': -1, 'TimedString': -1,
						'TimedShortSeq': True, 'TimedLongSeq': True, 'TimedLongSeq': True, 'TimedULongSeq': True,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': -1,
						'TimedBooleanSeq': -1, 'TimedOctetSeq': -1, 'TimedStringSeq': -1},
	'TimedShortSeq':	{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedLongSeq':		{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedUShortSeq':	{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedULongSeq':	{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedFloatSeq':	{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': False, 'TimedDouble': False, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': False, 'TimedDoubleSeq': False, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedDoubleSeq':	{'TimedShort': False, 'TimedLong': False, 'TimedLong': False, 'TimedULong': False,
						'TimedFloat': False, 'TimedDouble': False, 'TimedChar': False,
						'TimedBoolean': False, 'TimedOctet': False, 'TimedString': False,
						'TimedShortSeq': False, 'TimedLongSeq': False, 'TimedLongSeq': False, 'TimedULongSeq': False,
						'TimedFloatSeq': False, 'TimedDoubleSeq': False, 'TimedCharSeq': False,
						'TimedBooleanSeq': False, 'TimedOctetSeq': False, 'TimedStringSeq': False},
	'TimedCharSeq':		{'TimedShort': True, 'TimedLong': True, 'TimedLong': True, 'TimedULong': True,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': -1,
						'TimedBoolean': -1, 'TimedOctet': -1, 'TimedString': -1,
						'TimedShortSeq': True, 'TimedLongSeq': True, 'TimedLongSeq': True, 'TimedULongSeq': True,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': -1,
						'TimedBooleanSeq': -1, 'TimedOctetSeq': -1, 'TimedStringSeq': -1},
	'TimedBooleanSeq':	{'TimedShort': True, 'TimedLong': True, 'TimedLong': True, 'TimedULong': True,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': -1,
						'TimedBoolean': -1, 'TimedOctet': -1, 'TimedString': -1,
						'TimedShortSeq': True, 'TimedLongSeq': True, 'TimedLongSeq': True, 'TimedULongSeq': True,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': -1,
						'TimedBooleanSeq': -1, 'TimedOctetSeq': -1, 'TimedStringSeq': -1},
	'TimedOctetSeq':	{'TimedShort': True, 'TimedLong': True, 'TimedLong': True, 'TimedULong': True,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': -1,
						'TimedBoolean': -1, 'TimedOctet': -1, 'TimedString': -1,
						'TimedShortSeq': True, 'TimedLongSeq': True, 'TimedLongSeq': True, 'TimedULongSeq': True,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': -1,
						'TimedBooleanSeq': -1, 'TimedOctetSeq': -1, 'TimedStringSeq': -1},
	'TimedStringSeq':	{'TimedShort': True, 'TimedLong': True, 'TimedLong': True, 'TimedULong': True,
						'TimedFloat': True, 'TimedDouble': True, 'TimedChar': -1,
						'TimedBoolean': -1, 'TimedOctet': -1, 'TimedString': -1,
						'TimedShortSeq': True, 'TimedLongSeq': True, 'TimedLongSeq': True, 'TimedULongSeq': True,
						'TimedFloatSeq': True, 'TimedDoubleSeq': True, 'TimedCharSeq': -1,
						'TimedBooleanSeq': -1, 'TimedOctetSeq': -1, 'TimedStringSeq': -1}
}
